# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.oblique_BARTfit <- function(Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, phi_option, x0_option, a_theta, b_theta, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, verbose, print_every) {
    .Call('_obliqueBART_obliqueBART_fit', PACKAGE = 'obliqueBART', Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, phi_option, x0_option, a_theta, b_theta, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, verbose, print_every)
}

.oblique_BARTfit_lp <- function(Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, adaptive_aa_prob_option, alpha_dp, phi_option, a_theta, b_theta, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, verbose, print_every) {
    .Call('_obliqueBART_obliqueBART_fit_lp', PACKAGE = 'obliqueBART', Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, adaptive_aa_prob_option, alpha_dp, phi_option, a_theta, b_theta, mu0, tau, lambda, nu, M, nd, burn, thin, save_samples, verbose, print_every)
}

.probit_oblique_BARTfit_lp <- function(Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, adaptive_aa_prob_option, alpha_dp, phi_option, a_theta, b_theta, mu0, tau, M, nd, burn, thin, save_samples, verbose, print_every) {
    .Call('_obliqueBART_probit_obliqueBART_fit_lp', PACKAGE = 'obliqueBART', Y_train, tX_cont_train, tX_cat_train, tX_cont_test, tX_cat_test, unif_cuts, cutpoints_list, cat_levels_list, edge_mat_list, graph_split, graph_cut_type, aa_prob, adaptive_aa_prob_option, alpha_dp, phi_option, a_theta, b_theta, mu0, tau, M, nd, burn, thin, save_samples, verbose, print_every)
}

test_solver <- function() {
    .Call('_obliqueBART_test_solver', PACKAGE = 'obliqueBART')
}

test_solver2 <- function() {
    .Call('_obliqueBART_test_solver2', PACKAGE = 'obliqueBART')
}

test_maps_b_to_array <- function() {
    .Call('_obliqueBART_test_maps_b_to_array', PACKAGE = 'obliqueBART')
}

main <- function() {
    .Call('_obliqueBART_main', PACKAGE = 'obliqueBART')
}

test_max <- function() {
    .Call('_obliqueBART_test_max', PACKAGE = 'obliqueBART')
}

test_simplex3 <- function() {
    .Call('_obliqueBART_test_simplex3', PACKAGE = 'obliqueBART')
}

test_write_string <- function() {
    .Call('_obliqueBART_test_write_string', PACKAGE = 'obliqueBART')
}

